### PR TITLE
docs: Improve onboarding, define workflows

### LINKED ISSUE #25: Document project approach
### I'm submitting a... 
- [ ] Bug report
- [ ] Feature request
- [x] Documentation issue or request

### Current behavior 
There is no system in place to approach new projects.

### Expected behavior 
Projects should define a body of work that leads to a singular goal, e.g. "Create a public alt data API"

That body of work should then be broken down into the smallest shippable use cases. They must fit into a single issue and must be mergeable into master without breaking staging / early access builds. 

Some examples: "Add Query for retrieving experimental alt data", "Publicly log alt lookups by user id", "Add Command to populate new alt relations". 

We should then limit our Pull Requests to these minimal issues, which should lead to better reviewability, more frequent merges on master and fewer dependencies on in-progress changes.

This would also enable us to employ better team communication strategies, instead of seemingly random conversations about random projects.

##

**Additional Description**

### PR DESCRIPTION
**Pull request by Kaptard**
### What kind of change does this PR introduce?
- [ ] Bugfix
- [ ] New Feature
- [ ] Enhancement
- [ ] Refactor
- [ ] Build-related changes
- [x] Other, please describe:
Onboarding improvements

### Does this PR introduce a breaking change?
- [ ] Yes 
- [x] No

### Description
This PR makes it easier for newcomers to the project to find their way around and contribute.

Additionally, we established a concrete workflow for new projects and individual issues.

---

Resolves #25

### CODE REVIEW

**Comment by Kaptard** [comment]
@admutin would love to hear your opinion on this. Especially if you think these changes would've made the onboarding process easier and more transparent.

Best place to start comparing is the readme on the new branch. It should guide you to the rest of the changes.

**Comment by admutin** [comment]
First Time Setup:
I would add a paragraph for the project to be on WSL or native Linux or else the scripts wont work.

Daily Standup:
In my experience it is best to address problems, but NOT discuss them or their solutions in daily. Especially when our team grows bigger it takes a lot of time from everyone. 
Additionally I would appreciate to know what the person has done.
So in 3 short sentences: 
1) yesterday i did...
2) today i will do...
3) this problem blocks me

Git Conventions:
Maybe start with the branches to give the reader a high level overview. 
Also, mention the feature branches in some form.

The rest lgtm for now :)

**Comment by Kaptard** [comment]
> I would add a paragraph for the project to be on WSL or native Linux or else the scripts wont work.
Good point. It won't be necessary when #26 is resolved, but it's important for now.

> In my experience it is best to address problems, but NOT discuss them or their solutions in daily
What's the downside? 
For context, I don't believe we'll ever have teams of more than 5 people working on the same sprint.

An argument for daily standups is the habits we reinforce, where everyone keeps their eyes on the goal, everyone is aware of what others are doing, and, most importantly, everyone reflects on what they'll be doing themselves.

It may not be necessary on the daily if that person doesn't work every day - which given the nature of the project is reasonable. But it provides a reliable rhythm for those who can attend, as well as for those who seek the next time they can chime in.

**Review by admutin — APPROVED** [review]
LGTM

**Pull request merged**
